module.exports = {
	PERMISSIONS: {
		ADMIN_ANALYSIS_RELOAD_CACHE: 'Analysis Reload Cache',
		ADMIN_CLEAR_CACHE: 'Clear Cache',
		ADMIN_NAVY_WORKBOOK_SUMMARY_RELOAD_CACHE: 'Navy Workbook Summary Reload Cache',
		ADMIN_REFRESH_DATA_CATALOG: 'Refresh Data Catalog',
		ADMIN_SQL_BUILDER_RELOAD_CACHE: 'SQL Builder Reload Cache',
		ADMIN_USER_ROLE_EXPORT: 'User Role Export',
		ADMIN_MEGAMENU_EDIT: 'Megamenu Admin',
		ADMIN: 'Webapp Admin',
		ADMINISTER_NAVY_TICKMARKS: "Administer Navy Tickmarks",
		ADMINISTER_OSD_TICKMARKS: "Administer OSD Tickmarks",
		ALLOW_DATA_LOAD_HDFS_DIRECTORY: 'Allow Data Load #HDFS_DIRECTORY',
		ALLOW_FILE_CONTENT_SEARCH: 'Allow File Content Search',
		APPLY_NAVY_WB_TICKMARKS: "Apply Tickmarks Navy Workbooks",
		APPROVE_DATASET_MANAGEMENT: 'Approve Dataset Management #TABLE',
		ARMY_FEEDER_ADMIN: 'Army Feeder Admin',
		BUCKETING_CREATE_TICKET: "Bucketing Ticket Assign",
		BUCKETING_EXPORT_TICKETS: "Bucketing Export Tickets",
		CAN_BULK_GENERATE: "Bulk Generate",
		CAN_BULK_GENERATE_DFAS_FEEDER_WORKBOOKS: "Bulk Generate DFAS Feeder Workbooks",
		CAN_CREATE_DATASET: "Create Dataset",
		CAN_CREATE_PREFIXED_IMPALA_DATABASE: 'Create Impala Prefixed #PREFIX',
		CAN_DELETE_ARMY_FEEDER_TICKETS: 'Delete Army Feeder Ticket',
		CAN_DROP_PREFIXED_IMPALA_DATABASE_TABLE: 'Drop Impala Prefixed #PREFIX',
		CAN_EXPORT_UNLIMITED: 'Can Export SQL Builder Unlimited',
		CAN_IMPORT_TICKMARKS: "Import Tickmarks",
		CAN_LOAD_DATA_INTO_PREFIXED_IMPALA_TABLE: 'Create External Table Impala Prefixed #PREFIX',
		CAN_MANAGE_JOIN_PERMISSIONS: 'JOIN Permissions Management',
		CAN_PUBLISH_DATASET: "Publish Dataset",
		CAN_UPDATE_STATUS_TRACKER: "Update Data Status Tracker",
		CAN_VIEW_DATA_MIL: "CMS CDOPage",
		CAN_VIEW_ARMY_RECON: 'View Army Recon',
		CAN_VIEW_CDS_WORKFLOW: 'View CDS Workflow',
		CAN_VIEW_SITES_ALL: 'View All Sites',
		CREATE_TICKMARK_RULES: "Create Tickmark Rules",
		DARQ_ADMIN: (agency = null) => agency ? new RegExp(`^DARQ ${agency} Admin$`, 'i') : /^DARQ \w+ Admin$/i,
		DARQ_GROUP_ADMIN: (agency = null) => agency ? new RegExp(`^DARQ ${agency} Group Admin$`, 'i') : /^DARQ \w+ Group Admin$/i,
		DARQ_USER_ADMIN: (agency = null) => agency ? new RegExp(`^DARQ ${agency} User Admin$`, 'i') : /^DARQ \w+ User Admin$/i,
		DATA_REQUEST_ADMIN: 'Data Request Admin',
		DELETE_AWB: "Delete Workbooks",
		DFAS_FEEDER_ADMIN: 'DFAS Feeder Admin',
		EDIT_CMS: 'Edit CMS ',
		EDIT_DATA_STATUS_TRACKER: "Edit Data Status Tracker",
		EDIT_DATASET_MANAGEMENT: 'Edit Dataset Management #TABLE',
		EDIT_EDL_CONFIG: 'Edit EDL Config',
		EDIT_IMPALA_CSV_EXPORT_LIMIT: 'Edit Impala CSV Export Limit',
		EDIT_IMPALA_DESCRIBE_EXTENDED_BLACKLIST: 'Edit Impala DESCRIBE EXTENDED Blacklist',
		EDIT_MAGELLAN_DST: 'Edit Magellan DST',
		EDIT_MDM_EMAIL_RECIPIENTS: 'Edit MDM Recipients',
		EDIT_MDM_HIDDEN_TABLES: 'Edit MDM Visibility',
		EDIT_NAVY_WB_GLOBAL: "Edit Navy Workbooks Global",
		EDL_UPLOAD_PII_PHI_DATA: 'EDL Upload PII/PHI Data',
		EDL_UPLOAD_SENSITIVE_DATA: 'EDL Upload Sensitive Data',
		FBWT_AUTO_CLEAR: 'FBWT Auto Clear',
		GAMECHANGER_ADMIN: 'Gamechanger Admin',
		GAMECHANGER_BETA_TESTER: 'Gamechanger Beta Tester',
		IMPROPER_PAY_CREATE_TICKET: "Improper Pay Create Ticket",
		IMPROPER_PAY_MANAGER: "Improper Pay Manager",
		IMPROPER_PAY_SEND_EMAIL: 'Improper Pay Email',
		OSD: ' OSD',
		OSD_ANALYST: 'OSD Analyst',
		OWNER: ' Owner',
		PUBLISH_AWB: "Publish Workbooks",
		PUBLISH_NAVY_WB: "Publish Navy Workbooks",
		RELEASE_NOTES_ADMIN: 'Release Notes Admin',
		REVIEW_AWB_DFAS: "Review DFAS Workbooks",
		REVIEW_AWB_OSD: "Review OSD Workbooks",
		REVIEW_AWB: "Review Workbooks",
		REVIEW_NAVY_WB_FMO: "Review FMO Workbooks",
		REVIEW_NAVY_WB: "Review Navy Workbooks",
		ROLE_TESTER: "Role Tester",
		SQL_BUILDER_POWER_USER: 'SQL Builder Power User',
		SUBMIT_AWB: "Submit Workbooks",
		SUBMIT_NAVY_WB: "Submit Navy Workbooks",
		SUPER_ADMIN: "Webapp Super Admin",
		UNSUPER_ADMIN: "Tier 3 Support",
		UNRESTRICTED_QUERIES_IN_DB: 'Unrestricted Queries #DB',
		VIEW_ADVANA_PAGES: 'View Advana Pages',
		VIEW_ALL_AGENCIES: "View All Agencies",
		VIEW_ALL_SUB_ENTITIES: "View Agency Select All Subentities",
		VIEW_DARQ: /^DARQ .* User$/i,
		VIEW_DASHBOARD: "View Dashboard",
		VIEW_DATA_CATALOG: 'View Data Catalog',
		VIEW_DATA_REQUEST_DST_TOGGLE: "View Data Request DST Toggle",
		VIEW_DATA_ZONE_RESTRICTED_FILES: 'View Data Zone Restricted Files',
		VIEW_DATABASE_QUERY: 'View Database Query',
		VIEW_DATAPORTAL: "View Dataportal",
		VIEW_DATASET_MANAGEMENT: 'View Dataset Management',
		VIEW_DST_BIRDS_EYE: 'View DST Birds Eye',
		VIEW_EDA_DOCUMENTS: 'View EDA Documents',
		VIEW_EDL_HISTORY: "View EDL History",
		VIEW_FBWT: 'View FBWT',
		VIEW_FILESHARE: "View Fileshare",
		VIEW_FSD: "View FSD",
		FSD_ADMIN: "FSD Admin",
		VIEW_GAME_CHANGER: 'View Game Changer',
		VIEW_GL_TO_GL_RECON: 'View GL to GL Recon',
		VIEW_GUIDED_DATABASE_QUERY: 'View Guided Query',
		VIEW_HAISTACK: 'View Haistack',
		VIEW_HDFS_GLOBAL_SHARE: 'View HDFS Global Share',
		VIEW_HDFS_RECONS: 'View HDFS Recons',
		VIEW_HDFS_ROOT: 'View HDFS Root',
		VIEW_IMPROPER_PAY: 'View Improper Pay',
		VIEW_KPIS: 'View Kpis',
		VIEW_NAVY_DATA: 'View Navy Data',
		VIEW_NAVY_TICKMARKS: "View Navy Tickmarks",
		VIEW_NFR: 'View NFR',
		VIEW_PREFIXED_IMPALA_DATABASE: 'View Impala Prefixed #PREFIX',
		VIEW_QLIK: 'View Qlik',
		VIEW_SINGLE_ENTITY: "View Agency",
		VIEW_STREAMSETS: 'View Streamsets',
		VIEW_TICKMARKS: "View Tickmarks",
		VIEW_TRIFACTA: 'View Trifacta',
		VIEW_USER_MANAGEMENT: 'View User Management',
		VIEW_USER_METRICS: 'View User Metrics',
		VIEW_VARIANCE_ANALYTICS: "View Variance Analytics",
		VIEW_VARIANCE: "View Variance",
		WORKFLOW_ADMIN: ' #agency Admin',
		WORKFLOW_COORDINATOR: " #agency Coordinator",
		WORKFLOW_GROUP_ADMIN: ' #agency Group Admin',
		WORKFLOW_HQ: " #agency HQ",
		WORKFLOW_REVIEWER: " #agency Reviewer",
		WORKFLOW_SELF_ASSIGN: " Self Assign",
		WORKFLOW_TESTER: " #agency Tester",
		WORKFLOW_USER_ADMIN: ' #agency User Admin',
		WORKFLOW_VIEW_ONLY: " #agency View Only",
	},
}